version: "3"

networks:
    network:

services:
    db:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: root # De très bons credentials :p
            POSTGRES_DB: db
        restart: unless-stopped
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            network:

    app:
        build: .
        networks:
            network:
        ports:
            - "8000:8000"
        environment:
            IP: 0.0.0.0
            PORT: 8000
            POSTGRES_URL: 'db'
            POSTGRES_PASSWORD: root

    swagger:
        image: swaggerapi/swagger-ui
        expose:
            - 8080
        ports:
            - "8080:8080"
        environment:
            API_URL: 'app'
            SWAGGER_JSON: "/openapi.yml"
        networks:
            network:
        volumes:
            - "./openapi.yml:/openapi.yml"